In [30]:
import math
import numpy as np
import random

In [31]:
def fact(a):

    if(a==1):
        return 1
    else:
        return a*fact(a-1)

In [32]:
a = 2
b = 5

c = (a**2+b**2)**(0.5)
d = math.sqrt(c)

print("Hypo c = ", c)
print("sq root  d = ", d)

e = math.log(d)
print(e, c*d, c/d, c*math.sin(b), fact(10))

Hypo c =  5.385164807134504
sq root  d =  2.320595787106084
0.8418239574966185 12.496790764308276 2.3205957871060834 -5.163965256622914 3628800


In [34]:
a = np.array([[1, 2, 3], [4, 5, 6], [7, 10, 9]])
b = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

a*b, np.matmul(a, b), a.dot(b), a.T, np.linalg.inv(a)

(array([[ 1,  4,  9],
        [16, 25, 36],
        [49, 80, 81]]),
 array([[ 30,  36,  42],
        [ 66,  81,  96],
        [110, 136, 162]]),
 array([[ 30,  36,  42],
        [ 66,  81,  96],
        [110, 136, 162]]),
 array([[ 1,  4,  7],
        [ 2,  5, 10],
        [ 3,  6,  9]]),
 array([[-1.25      ,  1.        , -0.25      ],
        [ 0.5       , -1.        ,  0.5       ],
        [ 0.41666667,  0.33333333, -0.25      ]]))